---
title: "Lesson"
author: "Malene"
output: html_document
---

## Importing raw data

```{r setup}
# add new code chunk with Ctrl-Alt-I
library(vroom) # veeery fast to load data
library(here)
```

```{r loading files}
user_1_info_file <- here("data-raw/mmash/user_1/user_info.csv")
user_1_info_data <- vroom(user_1_info_file)

# you can use this to look at the columns
spec(user_1_info_data)
# col_double(): numeric (non-integer numbers) 
# col_character(): character data type

# only guessing until the first 100 rows, so if there is a lot of NA, then it will maybe assign the wrong type
#this code does not work because of the "..1" column
#user_1_info_data <- vroom(
 #   user_1_info_file,
  #  col_types = cols(
   #     ...1 = col_double(),
    #    Gender = col_character(),
     #   Weight = col_double(),
      #  Height = col_double(),
       # Age = col_double(),
  #      .delim = ","
  #  )
#)

# dplyr::select(): using "-" before the column name (or number) means to drop the column, 
# so in this case, we could drop the first column with col_select = -1

user_1_info_data <- vroom(
    user_1_info_file,
    col_select = -1,
    col_types = cols(
        Gender = col_character(),
        Weight = col_double(),
        Height = col_double(),
        Age = col_double()
    ),
    .name_repair = snakecase::to_snake_case
)

# look at the data
user_1_info_data

```


## Exercise: Import the saliva data

```{r loading in the salvia data}
user_1_saliva_file <- here("data-raw/mmash/user_1/saliva.csv")
user_1_saliva_data_prep <- vroom(user_1_saliva_file,
                                 col_select = -1) #already removing the first column
spec(user_1_saliva_data_prep)

user_1_saliva_data <- vroom(
    user_1_saliva_file,
    col_select = -1,
    col_types = cols(SAMPLES = col_character(),
  `Cortisol NORM` = col_double(),
  `Melatonin NORM` = col_double()),
    .name_repair = snakecase::to_snake_case
)

# take a look at it
user_1_saliva_data
```

## Import larger datasets
```{r loading in the big dtaa set}
user_1_rr_file <- here("data-raw/mmash/user_1/RR.csv")
user_1_rr_data_prep <- vroom(user_1_rr_file,
                             n_max = 100,
                             col_select = -1)
spec(user_1_rr_data_prep)

user_1_rr_data <- vroom(
    user_1_rr_file,
    col_select = -1,
    col_types = cols(
        ibi_s = col_double(),
        day = col_double(),
        # Converts to seconds
        time = col_time(format = "")
    ),
    .name_repair = snakecase::to_snake_case
)


```

To Knit, press ctrl + shift + k 

## Importing Athectigraph data

```{r loading in data}
user_1_acti_file <- here("data-raw/mmash/user_1/Actigraph.csv")
user_1_acti_data_prep <- vroom(user_1_acti_file,
                             n_max = 100,
                             col_select = -1)
spec(user_1_acti_data_prep)

user_1_acti_data_prep <- vroom(user_1_acti_file,
                             col_select = -1,
                             col_types = cols(Axis1 = col_double(),
                                              Axis2 = col_double(),
                                              Axis3 = col_double(),
                                              Steps = col_double(),
                                              HR = col_double(),
                                              `Inclinometer Off` = col_double(),
                                              `Inclinometer Standing` = col_double(),
                                              `Inclinometer Sitting` = col_double(),
                                              `Inclinometer Lying` = col_double(),
                                              `Vector Magnitude` = col_double(),
                                              day = col_double(),
                                              time = col_time(format = "")),
                             .name_repair = snakecase::to_snake_case)

```

